version: "3.7"
services:
  nodejs-api:
    build:
      context: ./src # dimuit86/node-api:latest
    container_name: nodejs-api
    restart: always
    ports:
    - "3000:3000"
    environment:
    - PGUSER=postgres
    - PGHOST=postgres
    - PGPASSWORD=postgres
    - PGDATABASE=testdb
    - PGPORT=5432
    networks:
        - mynet
    depends_on:
        - postgres
  postgres:
    image: postgres:latest
    container_name: postgres
    hostname: postgres
    extra_hosts:
        - "host.docker.internal:host-gateway"
    restart: always
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_DB=testdb
    ports: 
    - '5432:5432'
    networks:
        - mynet
    volumes:
    - ./postgres-data:/var/lib/postgresql/data
      # copy the sql script to create tables
    - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
networks:
   mynet:
    driver: bridge
volumes:
  postgres-data: