kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pgsql-data
  namespace: default
  annotations:
    volume.beta.kubernetes.io/storage-class: azure-disk
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi


