apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: default
  # annotations:
  #   service.beta.kubernetes.io/azure-dns-label-name: postgres
spec:
  type: ClusterIP
  selector:
    app: postgres
  ports:
    - port: 5432
