apiVersion: v1
kind: Secret
metadata:
  name: database-secret-config
  namespace: default
type: Opaque
data:
  user: cG9zdGdyZXM=
  password: cG9zdGdyZXM=
  url: cG9zdGdyZXM6Ly9wb3N0Z3Jlczpwb3N0Z3Jlc0Bwb3N0Z3Jlczo1NDMyL3Rlc3RkYg==
  database: dGVzdGRi